spring.application.name=ecsite
spring.datasource.url=jdbc:postgresql://db:5432/ecsite
spring.datasource.username=ecuser
spring.datasource.password=ecpass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
